### ISSUE TITLE
Doesn't pass promises-aplus/promises-tests

### ISSUE THREAD

**Issue by AsaAyers** [steelbrain/a-promise#4]
After I ran the tests I read the readme and saw 

> It doesn't support all the features yet, but It supports what a normal person needs to keep the code clean.

I figured I'd go ahead and post this anyway. Just close it if you like.

```js
// npm install promises-aplus-tests
var promisesAplusTests = require("promises-aplus-tests");

var Promise = require('a-promise')

var adapter = {
  resolved: function(value) {
    return Promise.resolve(value)
  },
  rejected: function(reason) {
    return Promise.reject(reason)
  },
  deferred: function() {
    return Promise.defer()
  },
}

promisesAplusTests(adapter, {}, function (err) {
  console.log(err)
})
```

it eventually says:

```
{ [Error: Test suite failed with 714 failures.] failures: 714 }

/tmp/foo/node_modules/promises-aplus-tests/node_modules/mocha/lib/reporters/spec.js:32
    return Array(indents).join('  ')
           ^
RangeError: Invalid array length
    at indent (/tmp/foo/node_modules/promises-aplus-tests/node_modules/mocha/lib/reporters/spec.js:32:12)
    at Runner.<anonymous> (/tmp/foo/node_modules/promises-aplus-tests/node_modules/mocha/lib/reporters/spec.js:56:17)
    at Runner.emit (events.js:117:20)
    at /tmp/foo/node_modules/promises-aplus-tests/node_modules/mocha/lib/runner.js:461:14
    at done (/tmp/foo/node_modules/promises-aplus-tests/node_modules/mocha/lib/runnable.js:206:5)
    at /tmp/foo/node_modules/promises-aplus-tests/node_modules/mocha/lib/runnable.js:226:9
    at onPromise2Fulfilled (/tmp/foo/node_modules/promises-aplus-tests/lib/tests/2.3.4.js:26:21)
    at /tmp/foo/node_modules/a-promise/Dist/Promise.js:102:65
    at /tmp/foo/node_modules/a-promise/Dist/Promise.js:67:15
    at Array.forEach (native)
```

interestingly `q` doesn't seem to finish the test. When I run with node 0.12 the native Promise passes all 872 tests.

**Comment by steelbrain** [comment]
Those incompatibilities are intentional, I had an choice to do stuff on next tick in constructor, resolve, reject and make OnResolve and OnReject a single function instead of an array of functions.
But I chose it to be like this to keep the codebase clean. and I haven't experienced a single bug in it in real life usage. Those tests just push it too hard.
